// Multiple agents per project: add agents (project folder + new worktree), setup command, sessions in
// both, layouts, file locks (synthetic PreToolUse hook calls), Changes for a worktree, merge (clean and
// conflicting), remove. Throwaway profile, throwaway git project under the trusted test folder.
// Real Claude Code sessions start, but no prompt is ever sent. Clipboard untouched.
const lib = require('./lib.cjs')
const { _electron } = require('playwright-core')
const fs = require('fs'), path = require('path'), { execSync } = require('child_process')
const scratch = lib.WORK, userData = path.join(scratch, 'agents-profile')
const root = path.join(lib.ROOT, 'node_modules/.hive-test')
const ws = path.join(root, 'ws')
const wtRoot = path.join(root, 'ws.worktrees')
for (const d of [userData, root]) fs.rmSync(d, { recursive: true, force: true })
const proj = path.join(ws, 'demo')
fs.mkdirSync(proj, { recursive: true })
const g = (cmd, cwd = proj) => execSync(`git ${cmd}`, { cwd, stdio: 'pipe' }).toString()
g('init -q -b main')
g('config user.email test@example.com')
g('config user.name Test')
fs.writeFileSync(path.join(proj, 'README.md'), '# Demo\n\nline one\n')
fs.writeFileSync(path.join(proj, 'app.txt'), 'shared file\n')
fs.writeFileSync(path.join(proj, '.gitignore'), '.env\nnode_modules/\n')
fs.writeFileSync(path.join(proj, '.env'), 'SECRET=local\n')
g('add -A')
g('commit -q -m init')

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
let pass = 0, fail = 0
const check = (name, ok, extra = '') => { if (ok) pass++; else fail++; console.log(ok ? 'PASS' : 'FAIL', name, extra) }
const shot = (page, n) => page.screenshot({ path: path.join(scratch, `agents-${n}.png`) })

;(async () => {
  lib.enableProviders(userData)
  const env = { ...process.env, HIVE_USER_DATA: userData }; delete env.ELECTRON_RUN_AS_NODE
  const app = await _electron.launch({ executablePath: lib.ELECTRON, args: [lib.ROOT], cwd: lib.ROOT, env })
  const page = await app.firstWindow()
  page.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
  await lib.fitWindow(app, page, { width: 1600, height: 950 })
  await sleep(1500)
  const inv = (ch, ...a) => page.evaluate(([c, x]) => window.hive.invoke(c, ...x), [ch, a])
  const project = async () => (await inv('workspace:refresh')).projects.find((p) => p.name === 'demo')
  await inv('workspace:open', ws); await sleep(800)
  await page.getByText('demo', { exact: true }).first().click(); await sleep(500)
  await inv('project:updateConfig', proj, { worktreeSetup: 'echo HIVE-SETUP-RAN' })

  // --- Agent 1 alone (added: projects start with none): the strip shows, with Add Agent
  const a1 = await lib.addAgent(inv, proj)
  await project(); await sleep(500)
  check('strip shows Agent 1', await page.locator('.agent-tab', { hasText: 'Agent 1' }).count() === 1)
  await shot(page, '1-single')

  // --- Add Agent 2 in the project folder and Agent 3 in a new worktree
  const a2 = await inv('agents:add', proj, { location: 'project' })
  check('Agent 2 added', a2.name === 'Agent 2' && !a2.worktree, JSON.stringify(a2))
  const a3 = await inv('agents:add', proj, { location: 'new-worktree', name: 'Reviewer', model: 'sonnet' })
  check('worktree agent added', !!a3.worktree && a3.worktree.branch === 'hive/reviewer', JSON.stringify(a3.worktree))
  const wtPath = a3.worktree.path
  check('worktree next to the workspace', path.resolve(wtPath).toLowerCase() === path.resolve(wtRoot, 'demo', 'reviewer').toLowerCase(), wtPath)
  check('.env copied into worktree', fs.existsSync(path.join(wtPath, '.env')))
  check('branch exists', g('branch --list hive/reviewer').includes('hive/reviewer'))
  check('needs setup', a3.needsSetup === true)
  const gi = await inv('agents:gitInfo', proj)
  check('gitInfo lists the worktree as used', gi.worktrees.some((w) => w.used && w.branch === 'hive/reviewer'), JSON.stringify(gi.worktrees))
  let p = await project()
  check('project has 3 agents', p.agents.length === 3, p.agents.map((a) => a.name).join(','))
  const dup = await inv('agents:add', proj, { location: 'project', name: 'agent 2' }).then(() => 'ok', (e) => e.message)
  check('duplicate name refused', /already an agent/.test(dup), dup)

  // --- Start Agent 1 and Agent 3 (setup first). No prompts are sent.
  await inv('session:start', proj, { agentId: a1.id })
  await lib.acceptClaudeTrust(inv, proj, a1.id)
  await inv('session:start', proj, { agentId: a3.id })
  await sleep(2500)
  const buf3 = await inv('pty:buffer', `session:${proj.toLowerCase()}#${a3.id}`)
  check('setup command ran in the agent terminal', buf3.includes('HIVE-SETUP-RAN'))
  await lib.acceptClaudeTrust(inv, proj, a3.id, 25000)
  await sleep(8000)
  let live = await inv('session:live')
  const l1 = live.find((l) => l.agentId === a1.id), l3 = live.find((l) => l.agentId === a3.id)
  check('two sessions live', !!l1 && !!l3, live.map((l) => `${l.agentId}:${l.status}`).join(' '))
  check('worktree session runs in the worktree', l3 && path.resolve(l3.cwd).toLowerCase() === path.resolve(wtPath).toLowerCase(), l3?.cwd)
  p = await project()
  check('setup cleared', !p.agents.find((a) => a.id === a3.id).needsSetup)
  check('launch folders per agent', fs.existsSync(path.join(proj, '.hive', `launch-${a1.id}`, 'settings.json')) && fs.existsSync(path.join(proj, '.hive', `launch-${a3.id}`, 'settings.json')))
  const argsOk = JSON.stringify(fs.readFileSync(path.join(proj, '.hive', `launch-${a3.id}`, 'settings.json'), 'utf8')).includes('PreToolUse')
  check('PreToolUse hook registered', argsOk)

  // --- Layouts
  await inv('project:updateConfig', proj, { layouts: ['columns2'] }); await inv('workspace:refresh'); await sleep(1200)
  check('two pane headers', await page.locator('.pane-header-bar').count() === 2)
  await shot(page, '2-columns2')
  await inv('project:updateConfig', proj, { layouts: ['grid'] }); await inv('workspace:refresh'); await sleep(1200)
  check('grid: 3 headers + empty pane', (await page.locator('.pane-header-bar').count()) === 3 && (await page.getByText('Empty pane').count()) === 1)
  await shot(page, '3-grid')
  await inv('project:updateConfig', proj, { layouts: ['columns3'] }); await inv('workspace:refresh'); await sleep(1200)
  await shot(page, '4-columns3')
  const visibleTerms = await page.locator('.terminal-host:not(.hidden)').count()
  check('two running terminals visible in 3 columns', visibleTerms === 2, String(visibleTerms))
  // Terminals sit in their own panes (not stacked in the first one)
  const rects = await page.evaluate(() => [...document.querySelectorAll('.terminal-host:not(.hidden)')].map((e) => Math.round(e.getBoundingClientRect().left)))
  check('terminals in separate panes', new Set(rects).size === rects.length && rects.length >= 2, JSON.stringify(rects))
  // Clicking a pane header focuses that agent
  await page.locator('.pane-header-bar', { hasText: 'Reviewer' }).locator('.agent-name').click(); await sleep(300)
  check('its pane header shows it focused', (await page.locator('.pane-header-bar.focused .agent-name').innerText()).includes('Reviewer'))

  // --- File locks via synthetic PreToolUse calls
  const launch = fs.readFileSync(path.join(proj, '.hive', `launch-${a1.id}`, 'settings.json'), 'utf8')
  const token = /Bearer ([0-9a-f]+)/.exec(launch)[1]
  const url = /"(http:\/\/127\.0\.0\.1:\d+\/hook)/.exec(launch.replace(/\\"/g, '"'))[1]
  const hook = (body) => fetch(url, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }).then((r) => r.json())
  // Agent 2 must run to share the folder with Agent 1.
  await inv('session:start', proj, { agentId: a2.id })
  await lib.acceptClaudeTrust(inv, proj, a2.id)
  await sleep(8000)
  live = await inv('session:live')
  const l2 = live.find((l) => l.agentId === a2.id)
  check('Agent 2 live', !!l2)
  const file = path.join(proj, 'app.txt')
  const pre = (sid, f = file, tool = 'Edit') => hook({ session_id: sid, hook_event_name: 'PreToolUse', tool_name: tool, tool_input: { file_path: f }, cwd: proj })
  let r = await pre(l1.sessionId)
  check('first edit allowed', !r.hookSpecificOutput, JSON.stringify(r))
  r = await pre(l2.sessionId)
  check('second agent blocked', r.hookSpecificOutput?.permissionDecision === 'deny' && /Agent 1 is editing app\.txt/.test(r.hookSpecificOutput.permissionDecisionReason), JSON.stringify(r))
  r = await pre(l1.sessionId)
  check('holder still allowed', !r.hookSpecificOutput)
  r = await pre(l2.sessionId, path.join(proj, 'README.md'))
  check('other file allowed', !r.hookSpecificOutput)
  r = await pre(l3.sessionId, path.join(wtPath, 'app.txt'))
  check('worktree copy of the file allowed', !r.hookSpecificOutput)
  r = await hook({ session_id: l2.sessionId, hook_event_name: 'PreToolUse', tool_name: 'Bash', tool_input: { command: 'echo' }, cwd: proj })
  check('non-edit tools ignored', !r.hookSpecificOutput)
  await sleep(400)
  p = await project()
  check('locked files published', JSON.stringify(p.agents.find((a) => a.id === a1.id).live.lockedFiles) === '["app.txt"]', JSON.stringify(p.agents.find((a) => a.id === a1.id).live.lockedFiles))
  await inv('project:updateConfig', proj, { fileLocks: 'ask' }); await inv('workspace:refresh')
  r = await pre(l2.sessionId)
  check('ask mode asks', r.hookSpecificOutput?.permissionDecision === 'ask')
  await inv('project:updateConfig', proj, { fileLocks: 'warn' }); await inv('workspace:refresh')
  r = await pre(l2.sessionId)
  check('warn mode adds context', !!r.hookSpecificOutput?.additionalContext && !r.hookSpecificOutput.permissionDecision)
  await inv('project:updateConfig', proj, { fileLocks: 'inherit' }); await inv('workspace:refresh')
  // Agent 1's turn ends: its claims are released
  await hook({ session_id: l1.sessionId, hook_event_name: 'Stop' }); await sleep(300)
  r = await pre(l2.sessionId)
  check('released after Stop; Agent 2 claims it', !r.hookSpecificOutput)
  r = await pre(l1.sessionId)
  check('now Agent 1 is blocked', r.hookSpecificOutput?.permissionDecision === 'deny' && /Agent 2 is editing/.test(r.hookSpecificOutput.permissionDecisionReason))
  await shot(page, '5-locks')

  // --- A new conversation started in the CLI (/clear, /new): its first prompt carries another session id
  // for the same launch, and Hive moves the agent to it.
  const run = /hook\?run=([0-9a-f]+)/.exec(launch)[1]
  const before = (await inv('session:live')).find((l) => l.agentId === a1.id).sessionId
  const newId = '33333333-4444-4555-8666-777777777777'
  await fetch(`${url}?run=${run}`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ session_id: newId, hook_event_name: 'UserPromptSubmit', cwd: proj }) })
  await sleep(800)
  const moved = (await inv('session:live')).find((l) => l.agentId === a1.id)
  check('follows a new conversation started in the CLI', moved.sessionId === newId && before !== newId, `${before} → ${moved.sessionId}`)
  const recs = JSON.parse(fs.readFileSync(path.join(proj, '.hive', 'sessions.json'), 'utf8')).sessions
  check('the new conversation is recorded for the agent', recs.some((s) => s.id === newId && s.agentId === a1.id), JSON.stringify(recs.map((s) => [s.id.slice(0, 8), s.agentId])))
  check('the old one stays in the list', recs.some((s) => s.id === before))

  // --- Changes tab for the worktree + merge
  fs.writeFileSync(path.join(wtPath, 'review.md'), '# Review notes\n')
  g('add -A', wtPath); g('commit -q -m "review notes"', wtPath)
  fs.appendFileSync(path.join(wtPath, 'README.md'), 'uncommitted line\n')
  const cs = await inv('git:status', wtPath, 'main')
  check('worktree changes since base', cs.files.some((f) => f.path === 'review.md') && cs.files.some((f) => f.path === 'README.md'), cs.files.map((f) => f.path + ':' + f.status).join(' '))
  const d = await inv('git:diff', wtPath, 'review.md', 'main')
  check('diff against base', d.original === '' && d.modified.includes('Review notes'))
  await page.locator('.tabs .tab', { hasText: 'Changes' }).click(); await sleep(600)
  await page.locator('.root-select').first().selectOption(a3.id); await sleep(1000)
  check('Changes tab shows worktree files', await page.getByText('review.md').count() > 0)
  await shot(page, '6-changes')
  const list = await inv('session:list', proj)
  check('worktree session recorded with cwd', list.some((s) => s.agentId === a3.id && s.cwd && s.branch === 'hive/reviewer'), JSON.stringify(list.map((s) => [s.agentId, s.branch])))
  const bs = await inv('agents:branchStatus', proj, a3.id)
  check('branch status', bs.ahead === 1 && bs.dirty === 1 && bs.into === 'main', JSON.stringify(bs))
  // Conflict: change README.md on main too
  fs.writeFileSync(path.join(proj, 'README.md'), '# Demo\n\nline one changed on main\n')
  g('commit -q -am "main change"')
  fs.writeFileSync(path.join(wtPath, 'README.md'), '# Demo\n\nline one changed by reviewer\n')
  const mainHead = g('rev-parse HEAD').trim()
  const conflict = await inv('agents:merge', proj, a3.id, { squash: true, message: 'Reviewer work', cleanup: false })
  check('conflict reported', !conflict.ok && conflict.conflicts?.includes('README.md'), JSON.stringify(conflict))
  check('main untouched after conflict', g('rev-parse HEAD').trim() === mainHead && g('status --porcelain').trim() === '')
  // Resolve on the branch by taking main's version, then merge cleanly
  fs.writeFileSync(path.join(wtPath, 'README.md'), '# Demo\n\nline one changed on main\n')
  g('add -A', wtPath); g('commit -q -m "take main readme"', wtPath)
  g('merge -q main -m sync', wtPath)
  await inv('session:stop', proj, a3.id); await sleep(3000)
  const merged = await inv('agents:merge', proj, a3.id, { squash: true, message: 'Reviewer work', cleanup: true })
  check('squash merge ok and cleaned up', merged.ok && merged.cleanedUp, JSON.stringify(merged))
  check('merge commit on main', g('log -1 --format=%s').trim() === 'Reviewer work' && fs.existsSync(path.join(proj, 'review.md')))
  check('worktree removed', !fs.existsSync(wtPath))
  check('branch deleted', !g('branch --list hive/reviewer').includes('hive/reviewer'))
  p = await project()
  check('agent removed', p.agents.length === 2)


  // --- Remove Agent 2 (must be stopped first)
  const refused = await inv('agents:remove', proj, a2.id, { deleteWorktree: false }).then(() => 'ok', (e) => e.message)
  check('remove refused while running', /Stop the agent/.test(refused))
  await inv('session:stop', proj); await sleep(3500)
  check('stop without agent stops all', (await inv('session:live')).length === 0)
  await inv('agents:remove', proj, a2.id, { deleteWorktree: false })
  p = await project()
  check('back to one agent', p.agents.length === 1)
  await page.locator('.tabs .tab', { hasText: 'Session' }).first().click(); await sleep(800)
  await shot(page, '7-after')

  console.log(`${pass}/${pass + fail} passed`)
  await app.close()
  for (const folder of [userData, root]) fs.rmSync(folder, { recursive: true, force: true })
})().catch(async (e) => { console.error(e); process.exit(1) })
