const lib = require('./lib.cjs')
const { _electron } = require('playwright-core')
const fs = require('fs'), path = require('path')
const scratch = lib.WORK, userData = path.join(scratch, 'cp-profile')
const ws = path.join(lib.ROOT, 'node_modules/.hive-test/ws')
const shots = path.join(scratch, 'cshots')
for (const d of [userData, ws, shots]) fs.rmSync(d, { recursive: true, force: true })
fs.mkdirSync(path.join(ws, 'demo'), { recursive: true }); fs.mkdirSync(shots, { recursive: true })
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const results = []
const check = (n, ok) => results.push(`${ok ? 'PASS' : 'FAIL'}  ${n}`)
;(async () => {
  lib.enableProviders(userData)
  const env = { ...process.env, HIVE_USER_DATA: userData }; delete env.ELECTRON_RUN_AS_NODE
  const app = await _electron.launch({ executablePath: lib.ELECTRON, args: [lib.ROOT], cwd: lib.ROOT, env })
  const page = await app.firstWindow()
  page.on('pageerror', (e) => results.push(`PAGEERROR ${e.message}`))
  await sleep(1500)
  const inv = (ch, ...a) => page.evaluate(([c, x]) => window.hive.invoke(c, ...x), [ch, a])
  const proj = path.join(ws, 'demo')
  await inv('workspace:open', ws); await sleep(800)
  await page.getByText('demo', { exact: true }).first().click()
  const agent = await lib.soloAgent(inv, proj)
  await inv('workspace:refresh')
  await inv('session:start', proj, { agentId: agent.id })
  await lib.acceptClaudeTrust(inv, proj, agent.id)
  await sleep(12000)
  const status = () => inv('session:live').then((l) => l[0]?.status + (l[0]?.statusMessage ? ` (${l[0].statusMessage})` : ''))
  console.log('status after start:', await status())
  await page.screenshot({ path: path.join(shots, '1-header.png') })
  const btn = page.locator('.pane-header-bar button[aria-label="Compact"]')
  check('compact button shown in the agent header', (await btn.count()) === 1)
  const ready = (await status()).startsWith('ready')
  check('new session reaches Ready (SessionStart hook arrives)', ready)
  check('empty session: button disabled', await btn.isDisabled())
  // The dialog via Session menu -> Compact Conversation.
  await page.locator('.menubar-item', { hasText: 'Session' }).first().click()
  await sleep(400)
  await page.getByText('Compact Conversation…').first().click()
  await sleep(600)
  check('dialog opens from the Session menu', (await page.locator('.dialog', { hasText: 'Compact demo?' }).count()) === 1)
  await page.locator('.compact-focus textarea').fill('keep the test notes')
  await page.screenshot({ path: path.join(shots, '2-dialog.png') })
  await page.locator('.dialog button', { hasText: /^\s*Compact\s*$/ }).click()
  await sleep(1500)
  const s1 = await status()
  console.log('status right after /compact:', s1)
  await sleep(4000)
  const raw = await inv('pty:buffer', lib.ptyKey(proj, agent.id))
  const i = raw.lastIndexOf('messages')
  console.log('RAW:', JSON.stringify(raw.slice(Math.max(0, i - 120), i + 60)))
  const s2 = await status()
  console.log('status 5 s later:', s2)
  check('refused compaction clears "Compacting" within seconds', !s2.includes('Compacting'))
  await page.screenshot({ path: path.join(shots, '3-after.png') })
  // Settings rows.
  await page.locator('.tab', { hasText: 'Settings' }).click(); await sleep(600)
  await page.locator('.settings-nav .row', { hasText: 'Sessions' }).click(); await sleep(300)
  check('project threshold row', (await page.getByText('Suggest compacting above').count()) >= 1)
  await page.screenshot({ path: path.join(shots, '5-project-settings.png') })
  await inv('session:stop', proj); await sleep(1500)
  console.log(results.join('\n'))
  await app.close()
  for (const d of [userData, path.join(lib.ROOT, 'node_modules/.hive-test')]) fs.rmSync(d, { recursive: true, force: true })
})().catch((e) => { console.error(e); console.log(results.join('\n')); process.exit(1) })
