// Keyboard shortcuts: Settings editor (record, chord, conflict, refused keys, remove, reset), project
// overrides, and some new defaults (Go to Project, layouts, next tab). Throwaway profile and workspace;
// no sessions started.
const lib = require('./lib.cjs')
const { _electron } = require('playwright-core')
const fs = require('fs'), path = require('path')
const scratch = lib.WORK, userData = path.join(scratch, 'keys-profile'), ws = path.join(scratch, 'keys-ws')
for (const d of [userData, ws]) fs.rmSync(d, { recursive: true, force: true })
for (const n of ['alpha', 'bravo']) fs.mkdirSync(path.join(ws, n), { recursive: true })
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
let pass = 0, fail = 0
const check = (name, ok, extra = '') => { if (ok) pass++; else fail++; console.log(ok ? 'PASS' : 'FAIL', name, extra) }
;(async () => {
  lib.enableProviders(userData)
  const env = lib.hiveEnv({ HIVE_USER_DATA: userData })
  const app = await _electron.launch({ executablePath: lib.ELECTRON, args: [lib.ROOT], cwd: lib.ROOT, env })
  const page = await app.firstWindow()
  page.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
  await lib.fitWindow(app, page, { width: 1400, height: 900 })
  await lib.appReady(page)
  await page.keyboard.press('Escape')
  const inv = (ch, ...a) => page.evaluate(([c, x]) => window.hive.invoke(c, ...x), [ch, a])
  await lib.openWorkspace(inv, page, ws)
  await page.getByText('alpha', { exact: true }).first().click(); await lib.until(async () => /alpha/.test(await page.locator('.project-header h1').innerText().catch(() => '')))
  const tab = () => page.locator('.tabs .tab.active').innerText()

  // New defaults
  await page.keyboard.press('Control+p'); await lib.until(async () => (await page.locator('.palette input[placeholder="Go to project"]').count()) === 1)
  check('Ctrl+P: Go to Project', await page.locator('.palette input[placeholder="Go to project"]').count() === 1)
  await page.keyboard.type('bravo'); await page.keyboard.press('Enter'); await lib.until(async () => /bravo/.test(await page.locator('.project-header h1').innerText().catch(() => '')))
  check('Go to Project opens it', /bravo/.test(await page.locator('.project-header h1').innerText()))
  await page.keyboard.press('Control+Tab'); await lib.until(async () => /Overview/.test(await tab().catch(() => '')))
  check('Ctrl+Tab: next project tab', /Overview/.test(await tab()), await tab())
  await page.keyboard.press('Control+Shift+Tab'); await lib.until(async () => /Session/.test(await tab().catch(() => '')))
  check('Ctrl+Shift+Tab: previous tab', /Session/.test(await tab()), await tab())
  for (const k of ['Alt+2', 'Alt+3', 'Alt+4', 'Alt+1']) { await page.keyboard.press(k); await sleep(150) }
  check('tab shortcuts never hide the sidebar', (await page.locator('.project-row').count()) === 2)
  await page.keyboard.press('Control+Alt+2'); await lib.until(async () => (await inv('workspace:refresh')).projects.find((x) => x.name === 'bravo')?.config.layouts?.[0] === 'columns2')
  const p = (await inv('workspace:refresh')).projects.find((x) => x.name === 'bravo')
  check('Ctrl+Alt+2: two-column layout', p.config.layouts[0] === 'columns2', JSON.stringify(p.config.layouts))
  await page.keyboard.press('Control+Alt+1'); await lib.until(async () => (await inv('workspace:refresh')).projects.find((x) => x.name === 'bravo')?.config.layouts?.[0] === 'single')

  // Settings → Keyboard Shortcuts
  await page.keyboard.press('Control+,'); await lib.until(async () => (await page.locator('.settings-nav .row', { hasText: 'Keyboard Shortcuts' }).count()) > 0)
  await page.locator('.settings-nav .row', { hasText: 'Keyboard Shortcuts' }).click(); await lib.until(async () => (await page.locator('.kb-table tr:not(.kb-cat)').count()) > 60)
  check('editor lists commands', (await page.locator('.kb-table tr:not(.kb-cat)').count()) > 60, String(await page.locator('.kb-table tr:not(.kb-cat)').count()))
  await page.locator('.kb-toolbar input').fill('Show Notifications'); await sleep(200)
  const row = page.locator('.kb-table tr', { hasText: 'Show Notifications' }).first()
  await row.locator('.icon-btn[aria-label^="Change shortcut"]').click(); await lib.until(async () => /Press the keys/.test(await row.innerText()))
  check('recording prompt', /Press the keys/.test(await row.innerText()))
  await page.keyboard.press('Control+Alt+J'); await lib.until(async () => (await inv('settings:get')).keybindings['view.notifications'] === 'Mod+Alt+J', 10000)
  let s = await inv('settings:get')
  check('recorded Ctrl+Alt+J', s.keybindings['view.notifications'] === 'Mod+Alt+J', JSON.stringify(s.keybindings))
  check('row shows Changed', /Changed/.test(await row.innerText()))
  await page.screenshot({ path: path.join(scratch, 'keys-1-settings.png') })
  await page.locator('.settings-top input.input').first().click()
  await page.keyboard.press('Control+Alt+J'); await lib.until(async () => (await page.locator('.notif-panel').count()) === 1)
  check('new shortcut works', await page.locator('.notif-panel').count() === 1)
  await page.keyboard.press('Escape'); await sleep(200)
  // Chord
  await row.locator('.icon-btn[aria-label^="Change shortcut"]').click(); await sleep(200)
  await page.keyboard.press('Control+K'); await sleep(300); await page.keyboard.press('Control+J'); await lib.until(async () => (await inv('settings:get')).keybindings['view.notifications'] === 'Mod+K Mod+J')
  s = await inv('settings:get')
  check('chord recorded', s.keybindings['view.notifications'] === 'Mod+K Mod+J', s.keybindings['view.notifications'])
  // Refused key
  await row.locator('.icon-btn[aria-label^="Change shortcut"]').click(); await sleep(200)
  await page.keyboard.press('Control+C'); await lib.until(async () => (await page.locator('.toast', { hasText: "can't be used" }).count()) >= 1, 10000)
  check('Ctrl+C refused', (await page.locator('.toast', { hasText: "can't be used" }).count()) >= 1 && (await inv('settings:get')).keybindings['view.notifications'] === 'Mod+K Mod+J')
  // Conflict asks
  await row.locator('.icon-btn[aria-label^="Change shortcut"]').click(); await sleep(200)
  await page.keyboard.press('Control+Shift+P'); await lib.until(async () => (await page.locator('.dialog', { hasText: 'Shortcut already in use' }).count()) === 1, 10000)
  check('conflict asks first', await page.locator('.dialog', { hasText: 'Shortcut already in use' }).count() === 1)
  await page.locator('.dialog button', { hasText: 'Cancel' }).click(); await sleep(200)
  // Remove, then reset
  await row.locator('.icon-btn[aria-label="Remove shortcut"]').click(); await lib.until(async () => (await inv('settings:get')).keybindings['view.notifications'] === null)
  check('removed', (await inv('settings:get')).keybindings['view.notifications'] === null)
  await row.locator('.icon-btn[aria-label^="Reset to default"]').click(); await lib.until(async () => !('view.notifications' in (await inv('settings:get')).keybindings))
  check('reset to default', !('view.notifications' in (await inv('settings:get')).keybindings))

  // Project override: alpha gets Alt+F for Files; bravo keeps Alt+4
  await page.keyboard.press('Escape')
  if (!(await page.locator('.project-row').count())) await page.locator('.activity-btn[aria-label="Projects"]').click()
  await sleep(300)
  console.log('rows before alpha', await page.locator('.project-row').count(), await page.evaluate(() => document.querySelector('.activity-btn.active')?.getAttribute('aria-label')))
  await page.locator('.project-row', { hasText: 'alpha' }).click(); await lib.until(async () => /alpha/.test(await page.locator('.project-header h1').innerText().catch(() => '')))
  await page.locator('.tabs .tab', { hasText: 'Settings' }).click(); await lib.until(async () => /Settings/.test(await tab().catch(() => '')))
  await page.locator('.settings-nav .row, .psettings-nav .row, .row', { hasText: 'Keyboard Shortcuts' }).first().click(); await lib.until(async () => (await page.locator('.kb-table').innerText().catch(() => '')).includes('Go to Files'))
  check('project editor lists only project/session commands', !(await page.locator('.kb-table').innerText()).includes('Toggle Sidebar') && (await page.locator('.kb-table').innerText()).includes('Go to Files'))
  console.log('rows after kb nav', await page.locator('.project-row').count())
  const frow = page.locator('.kb-table tr', { hasText: 'Go to Files' }).first()
  await frow.locator('.icon-btn[aria-label^="Change shortcut"]').click(); await sleep(200)
  await page.keyboard.press('Alt+F'); await lib.until(async () => (await inv('workspace:refresh')).projects.find((x) => x.name === 'alpha')?.config.keybindings?.['project.tab.files'] === 'Alt+F', 10000)
  const alpha = (await inv('workspace:refresh')).projects.find((x) => x.name === 'alpha')
  check('saved in the project', alpha.config.keybindings?.['project.tab.files'] === 'Alt+F', JSON.stringify(alpha.config.keybindings))
  await page.screenshot({ path: path.join(scratch, 'keys-2-project.png') })
  console.log('rows after record', await page.locator('.project-row').count())
  await page.locator('.tabs .tab', { hasText: 'Session' }).first().click(); await sleep(200)
  await page.keyboard.press('Alt+F'); await lib.until(async () => /Files/.test(await tab().catch(() => '')))
  console.log('rows after altF', await page.locator('.project-row').count())
  check('Alt+F opens Files in alpha', /Files/.test(await tab()), await tab())
  await page.locator('.project-row', { hasText: 'bravo' }).click(); await lib.until(async () => /bravo/.test(await page.locator('.project-header h1').innerText().catch(() => '')))
  await page.locator('.tabs .tab', { hasText: 'Session' }).first().click(); await lib.until(async () => /Session/.test(await tab().catch(() => '')))
  await page.keyboard.press('Alt+F'); await sleep(500) // A fixed wait on purpose: this checks that Alt+F does NOT switch tabs in bravo.
  check('Alt+F does nothing in bravo', /Session/.test(await tab()), await tab())
  await page.keyboard.press('Alt+4'); await lib.until(async () => /Files/.test(await tab().catch(() => '')))
  check('bravo keeps Alt+4', /Files/.test(await tab()), await tab())

  // Shortcuts dialog reflects changes and links to the editor
  await page.locator('.project-row', { hasText: 'alpha' }).click(); await lib.until(async () => /alpha/.test(await page.locator('.project-header h1').innerText().catch(() => '')))
  await page.locator('.project-header h1').click()
  await page.keyboard.press('Control+K'); await page.keyboard.press('Control+S'); await lib.until(async () => (await page.locator('.dialog').innerText().catch(() => '')).includes('Alt+F'))
  check('shortcuts dialog shows the project key', (await page.locator('.dialog').innerText()).includes('Alt+F'))
  await page.locator('.dialog button', { hasText: 'Customise' }).click(); await lib.until(async () => (await page.locator('.kb-editor').count()) === 1)
  check('Customise opens the editor', await page.locator('.kb-editor').count() === 1)
  await app.close()
  console.log(`\n${pass} passed, ${fail} failed`)
  process.exit(fail ? 1 : 0)
})().catch((e) => { console.error(e); process.exit(1) })
