// Visual check of the provider screens on a fresh profile: banner, Settings → Providers, Agent Setup, Add Agent.
const lib = require('./lib.cjs')
const { _electron } = require('playwright-core')
const fs = require('fs')
const path = require('path')
const scratch = lib.WORK
const userData = path.join(scratch, 'pv-profile')
const ws = path.join(scratch, 'pv-ws')
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const results = []
const check = (name, ok, extra = '') => results.push(`${ok ? 'PASS' : 'FAIL'} ${name}${ok || !extra ? '' : ` (${extra})`}`)

;(async () => {
  for (const d of [userData, ws]) fs.rmSync(d, { recursive: true, force: true })
  fs.mkdirSync(path.join(ws, 'demo'), { recursive: true })
  const env = { ...process.env, HIVE_USER_DATA: userData, HIVE_API_PORT: '47893' }
  delete env.ELECTRON_RUN_AS_NODE
  const app = await _electron.launch({ executablePath: lib.ELECTRON, args: [lib.ROOT], env })
  const page = await app.firstWindow()
  page.on('pageerror', (e) => results.push(`PAGEERROR ${e.message}`))
  await page.setViewportSize({ width: 1400, height: 850 }).catch(() => {})
  await sleep(2500)
  const inv = (ch, ...a) => page.evaluate(([c, x]) => window.hive.invoke(c, ...x), [ch, a])
  check('no setup dialog on a fresh install', (await page.locator('.dialog', { hasText: 'Agent Setup' }).count()) === 0)
  check('welcome offers choosing agents', (await page.locator('.welcome-link', { hasText: 'Choose your coding agents' }).count()) === 1)
  await inv('workspace:open', ws)
  await sleep(1200)
  const banner = page.locator('.providers-banner')
  check('banner: no coding agents', /No coding agents are turned on/.test(await banner.innerText().catch(() => '')))
  await page.getByText('demo', { exact: true }).first().click()
  await sleep(500)
  await page.screenshot({ path: path.join(scratch, 'pv-1-banner.png') })
  await banner.getByRole('button', { name: 'Choose providers' }).click()
  await sleep(800)
  check('settings opens at Providers', (await page.locator('.settings-group h2', { hasText: 'Providers' }).count()) === 1)
  await page.screenshot({ path: path.join(scratch, 'pv-2-providers.png') })
  const s0 = await inv('settings:get')
  check('fresh: Claude Code off', s0.providers['claude-code'].enabled === false)
  await page.locator('.provider-row', { hasText: 'Claude Code' }).locator('.switch, [role=switch], input[type=checkbox]').first().click()
  await sleep(1500)
  const s1 = await inv('settings:get')
  check('toggle turns Claude Code on', s1.providers['claude-code'].enabled === true)
  check('banner gone once on (Claude installed)', (await page.locator('.providers-banner').count()) === 0, await page.locator('.providers-banner').innerText().catch(() => ''))
  await page.locator('.settings-nav .row', { hasText: 'Claude Code' }).click()
  await sleep(500)
  await page.screenshot({ path: path.join(scratch, 'pv-3-claude-page.png') })
  check('Claude page has its settings', (await page.locator('.setting', { hasText: 'Enable the Bypass permissions option' }).count()) === 1)
  await inv('settings:update', { providers: { 'claude-code': { defaultModel: 'sonnet' } } })
  await sleep(300)
  // Agent Setup
  await page.evaluate(() => window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' })))
  await page.locator('.activitybar .activity, .activity-bar .activity').first().click().catch(() => undefined)
  await sleep(300)
  await page.evaluate(() => (window).__hiveRun?.('help.agentSetup'))
  // Open Agent Setup through the command palette.
  await page.keyboard.press('Control+Shift+P')
  await sleep(300)
  await page.keyboard.type('Agent Setup')
  await sleep(300)
  await page.keyboard.press('Enter')
  await sleep(1200)
  const setup = page.locator('.dialog', { hasText: 'Agent Setup' })
  check('Agent Setup opens', (await setup.count()) === 1)
  check('Agent Setup shows Claude Code', /Claude Code \d/.test(await setup.innerText().catch(() => '')))
  await page.screenshot({ path: path.join(scratch, 'pv-4-setup.png') })
  await page.keyboard.press('Escape')
  await sleep(300)
  // Add Agent
  await inv('project:setActive', path.join(ws, 'demo'), true)
  await page.evaluate(() => window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' })))
  await page.keyboard.press('Control+Shift+P')
  await sleep(300)
  await page.keyboard.type('Add Agent…')
  await sleep(300)
  await page.keyboard.press('Enter')
  await sleep(1200)
  const add = page.locator('.dialog', { hasText: 'Add an agent' })
  check('Add Agent has a coding agent choice', (await add.locator('.provider-choice .choice').count()) >= 1)
  await page.screenshot({ path: path.join(scratch, 'pv-5-add-agent.png') })
  await page.keyboard.press('Escape')
  const cfg = JSON.parse(fs.readFileSync(path.join(userData, 'config.json'), 'utf8'))
  check('config saved as version 2 with the legacy block', cfg.version === 2 && cfg.settings.claude?.defaultModel === 'sonnet', JSON.stringify(cfg.settings.claude))
  await app.close()
  console.log(results.join('\n'))
})().catch((e) => {
  console.error(e)
  console.log(results.join('\n'))
  process.exit(1)
})
