// Hive's end-to-end suites (tests/e2e/<name>.cjs), for run.mjs, the affected-suite map and their tests.
// needs: claude = starts the real Claude Code; codex = the signed-in test Codex home; packaged = dist/win-unpacked.
// Suites that start a real CLI (claude, codex) share it with each other, so they run one at a time, in a lane beside
// the others; those marked serial (with why) and the installer's run last, alone; every other suite is safe to run
// beside others (its own profile, folders and Agent API port). Sorted by name, so suites added on different
// branches land in different places (tests/e2esuites.test.ts checks).
export const SUITES = [
  { name: 'about' },
  { name: 'agents' },
  { name: 'agents-ui' },
  { name: 'agentview', needs: ['claude'] },
  { name: 'assistant' },
  { name: 'assistant-control' },
  { name: 'assistantend' },
  { name: 'assistantoverview' },
  { name: 'assistantside' },
  { name: 'attention' },
  { name: 'automode' },
  { name: 'background' },
  { name: 'banners' },
  { name: 'bell' },
  { name: 'board' },
  { name: 'boardscope' },
  { name: 'boardscroll' },
  { name: 'bridgereport' },
  { name: 'bursts' },
  { name: 'busy' },
  { name: 'cardchip' },
  { name: 'carddialog' },
  { name: 'cardloop' },
  { name: 'changes' },
  { name: 'claude-real', needs: ['claude'] },
  { name: 'closewindow' },
  { name: 'codex', needs: ['codex'] },
  { name: 'codex-background', needs: ['codex'] },
  { name: 'codex-extra', needs: ['codex'] },
  { name: 'codex-handover', needs: ['codex'] },
  { name: 'codex-setup', needs: ['codex'] },
  { name: 'compact', needs: ['claude'] },
  { name: 'context' },
  { name: 'ctxpercent' },
  { name: 'dialogs' },
  { name: 'doingmove' },
  { name: 'donemove' },
  { name: 'drafts' },
  { name: 'editor' },
  { name: 'filelinks' },
  { name: 'files' },
  { name: 'footerfit' },
  { name: 'icons' },
  { name: 'image' },
  { name: 'inbox', serial: 'window focus' },
  { name: 'isolation' },
  { name: 'keys' },
  { name: 'launchrace' },
  { name: 'loadfail' },
  { name: 'longsession' },
  { name: 'mcp' },
  { name: 'mode', needs: ['claude'] },
  { name: 'models' },
  { name: 'narrowmain' },
  { name: 'numbers' },
  { name: 'overview' },
  { name: 'packaged', needs: ['packaged'] },
  { name: 'packaged-mcp', needs: ['packaged'] },
  { name: 'packaged-progress', needs: ['packaged'] },
  { name: 'packaged-transcript', needs: ['packaged'] },
  { name: 'pages' },
  { name: 'paneheader' },
  { name: 'perfcompare' },
  { name: 'performance' },
  { name: 'perftable' },
  { name: 'pin' },
  { name: 'plan', needs: ['claude'] },
  { name: 'progress', serial: 'window focus' },
  { name: 'progressreport' },
  { name: 'providers' },
  { name: 'quit' },
  { name: 'quitwait' },
  { name: 'rail' },
  { name: 'recent' },
  { name: 'rendercrash' },
  { name: 'reorder' },
  { name: 'replysize' },
  { name: 'resize' },
  { name: 'restart' },
  { name: 'resume' },
  { name: 'resumeall' },
  { name: 'review' },
  { name: 'sessionname' },
  { name: 'sessionorigin' },
  { name: 'skillaudience' },
  { name: 'skilldelivery' },
  { name: 'skills', serial: 'the shared Codex test home' },
  { name: 'startall' },
  { name: 'startfail' },
  { name: 'storage' },
  { name: 'swap' },
  { name: 'tabstrip' },
  { name: 'taskbar', serial: 'window focus' },
  { name: 'taskoverview' },
  { name: 'templates' },
  { name: 'templateshare' },
  { name: 'tipcorner' },
  { name: 'tips' },
  { name: 'transcript' },
  { name: 'unmerged' },
  { name: 'unpricedcost' },
  { name: 'unsaved' },
  { name: 'update' },
  { name: 'windows' },
  { name: 'wsmove' },
  { name: 'wsoverview' },
  { name: 'wtrecreate' }
]
