// Writes THIRD_PARTY_NOTICES.md: the licence of every package that ships inside Hive — the main
// process's runtime dependencies and the libraries bundled into the renderer — with their full texts.
// Run by `npm run build`; commit the result. Build-only tools (vite, electron-builder, sharp…) are not
// shipped and not listed.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

// Bundled into the renderer by Vite (devDependencies because they are compiled in, not installed).
const RENDERER = ['react', 'react-dom', '@xterm/xterm', '@xterm/addon-fit', '@xterm/addon-web-links', '@xterm/addon-webgl', 'monaco-editor', 'dompurify', 'marked', 'zustand', '@vscode/codicons']
const roots = [...new Set(['electron', ...Object.keys(pkg.dependencies ?? {}), ...RENDERER])]

/** Where a package is installed, looking in the requiring package's own node_modules first. */
function locate(name, from) {
  for (let dir = from; dir && dir.startsWith(root); dir = dirname(dir)) {
    const p = join(dir, 'node_modules', name)
    if (existsSync(join(p, 'package.json'))) return p
    if (dir === root) break
  }
  return null
}

const found = new Map()
function walk(name, from, runtimeOnly) {
  const dir = locate(name, from)
  // Type definitions are compile-time only.
  if (!dir || name.startsWith('@types/')) return
  const meta = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
  const id = `${meta.name}@${meta.version}`
  if (found.has(id)) return
  found.set(id, { meta, dir })
  // Electron's own dependencies only download its binary at install time; they don't ship.
  if (!runtimeOnly) return
  for (const dep of [...Object.keys(meta.dependencies ?? {}), ...Object.keys(meta.optionalDependencies ?? {})]) walk(dep, dir, true)
}
for (const name of roots) walk(name, root, name !== 'electron')

const licenceOf = (meta) =>
  typeof meta.license === 'string' ? meta.license : meta.license?.type ?? (Array.isArray(meta.licenses) ? meta.licenses.map((l) => l.type ?? l).join(' OR ') : 'see licence text')
const repoOf = (meta) => {
  const r = typeof meta.repository === 'string' ? meta.repository : meta.repository?.url
  return (r ?? meta.homepage ?? '').replace(/^git\+/, '').replace(/\.git$/, '').replace(/^git:\/\//, 'https://').replace(/^github:/, 'https://github.com/')
}
const licenceFiles = (dir) =>
  readdirSync(dir)
    .filter((f) => /^(licen[cs]e|copying|notice|thirdpartynotices)/i.test(f))
    .sort()
    .map((f) => ({ file: f, text: readFileSync(join(dir, f), 'utf8').replace(/\r\n/g, '\n').trim() }))

const list = [...found.values()].sort((a, b) => a.meta.name.localeCompare(b.meta.name))
const out = [
  '# Third-party notices',
  '',
  'Hive is licensed under the [MIT License](LICENSE). It includes the open-source software listed below, each under its own licence, reproduced in full further down.',
  '',
  'Hive runs on [Electron](https://www.electronjs.org/), which includes Chromium, Node.js and other components. Their licences ship with the app, in `LICENSE.electron.txt` and `LICENSES.chromium.html` in the folder Hive is installed in.',
  '',
  'This file is generated by `scripts/licenses.mjs` during `npm run build`.',
  '',
  '| Package | Version | Licence |',
  '|---|---|---|',
  ...list.map(({ meta }) => {
    const repo = repoOf(meta)
    return `| ${repo ? `[${meta.name}](${repo})` : meta.name} | ${meta.version} | ${licenceOf(meta)} |`
  }),
  ''
]
for (const { meta, dir } of list) {
  out.push(`## ${meta.name} ${meta.version}`, '', `Licence: ${licenceOf(meta)}`, '')
  const files = licenceFiles(dir)
  if (!files.length) out.push(`No licence file is included in the package; it is published under ${licenceOf(meta)}.`, '')
  for (const f of files) out.push(...(files.length > 1 ? [`*${f.file}*`, ''] : []), '```text', f.text, '```', '')
}
writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), out.join('\n'))
console.log(`THIRD_PARTY_NOTICES.md: ${list.length} packages`)
